ALTER TABLE GROUPS DROP INDEX GROUPS_NAME_UINDEX;
ALTER TABLE SUBJECT_CATEGORYS DROP INDEX SUBJECT_CATEGORYS_TITLE_UINDEX;
ALTER TABLE SUBJECTS DROP INDEX SUBJECTS_NAME_UINDEX;


DROP TABLE IF EXISTS study;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS subject_categorys;
DROP TABLE IF EXISTS teachers;
